version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: container_mariadb
#    restart: always
    networks:
      - inception_network
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /Users/hommayunosuke/Documents/ft.dir/Rank05/Inception/data/mysql:/var/lib/mysql

#  nginx:
#    build: ./requirements/nginx
#    container_name: container_nginx
#    networks:
#      - inception_network
#    ports:
#      - "443:443"
#    restart: always
#
#  wordpress:
#    build: ./requirements/wordpress
#    container_name: container_wordpress
#    networks:
#      - inception_network
#    env_file:
#      - .env
#    depends_on:
#      - mariadb


# volumesはコンテナ間でデータを共有したり、データを永続的に残せる
# networksはコンテナ間の通信を可能にする
# buildはディレクトリを指定すれば、そのディレクトリにあるDockerfileを使ってイメージを作成する

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      # ホストマシンの特定のファイルやディレクトリをコンテナの特定の場所にマウント
      # type: none o: bindでもupはできるが、怪しい
      type: bind
      device: $PWD/data/mysql
      # device: /home/hyunosuk/data/mysql
      # o: bindをつけないとエラーが出てしまう
      # 冗長じゃないのかな？
      o: bind

networks:
  inception_network: