version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: container_mariadb
    networks:
      - inception_network
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - $PWD/../data/mysql:/var/lib/mysql
#      - /Users/hommayunosuke/Documents/ft.dir/Rank05/Inception/data/mysql:/var/lib/mysql
#       なんかこれだとうまくいかないから一旦は下手書き
#       TODO:チェック
#      - wordpress-data:/var/lib/mysql
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: container_nginx
    networks:
      - inception_network
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - $PWD/../data/wordpress:/var/www/html/wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: container_wordpress
    networks:
      - inception_network
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - $PWD/../data/wordpress:/var/www/html/wordpress
    restart: always


# volumesはコンテナ間でデータを共有したり、データを永続的に残せる
# networksはコンテナ間の通信を可能にする
# buildはディレクトリを指定すれば、そのディレクトリにあるDockerfileを使ってイメージを作成する

#  _だとうまくいかなかったが、-だとうまくいった理由不明
volumes:
  wordpress-data:
    driver: local
    driver_opts:
      # ホストマシンの特定のファイルやディレクトリをコンテナの特定の場所にマウント
      # type: none o: bindでもupはできるが、怪しい
      type: none
      device: $PWD/../data/wordpress
      # device: /home/hyunosuk/data/mysql
      # o: bindをつけないとエラーが出てしまう
      # 冗長じゃないのかな？
      o: bind

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/../data/mysql
      o: bind

networks:
  inception_network: