version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/
#      - /home/hyunosuk/data/:/var/www/html/
#    depends_on:
#      - wordpress
    restart: always
#    networks:
#      - inception_network

#  wordpress:
#    container_name: wordpress
#    build: ./requirements/wordpress
#    volumes:
#      - wp_web_data:/var/www/html
#    #depends_on:
#    restart: always
#    networks:
#      - inception_network

# volumesはコンテナ間でデータを共有したり、データを永続的に残せる
# networksはコンテナ間の通信を可能にする
# buildはディレクトリを指定すれば、そのディレクトリにあるDockerfileを使ってイメージを作成する

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      # ホストマシンの特定のファイルやディレクトリをコンテナの特定の場所にマウント
      # type: none o: bindでもupはできるが、怪しい
      type: bind
      device: /Users/hommayunosuke/Documents/ft.dir/Rank05/Inception/data/mysql
#      device: /home/hyunosuk/data/mysql
      # o: bindをつけないとエラーが出てしまう
      o: bind