version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:42
    container_name: container_mariadb
    networks:
      - inception_network
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - ${VOLUME_PATH}db:/var/lib/mysql
#      - mariadb-data:/var/lib/mysql
#      - /Users/hommayunosuke/Documents/ft.dir/Rank05/Inception/data/mysql:/var/lib/mysql
#       なんかこれだとうまくいかないから一旦は下手書き
#       TODO:チェック
#      - wordpress-data:/var/lib/mysql
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:42
    container_name: container_nginx
    networks:
      - inception_network
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - ${VOLUME_PATH}wordpress:/var/www/html/wordpress
#      - wordpress-data:/var/www/html/wordpress
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:42
    container_name: container_wordpress
    networks:
      - inception_network
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ${VOLUME_PATH}wordpress:/var/www/html/wordpress
#      - wordpress-data:/var/www/html/wordpress
    restart: always


# volumesはコンテナ間でデータを共有したり、データを永続的に残せる
# networksはコンテナ間の通信を可能にする
# buildはディレクトリを指定すれば、そのディレクトリにあるDockerfileを使ってイメージを作成する

#  _だとうまくいかなかったが、-だとうまくいった理由不明
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}db
      o: bind

  wordpress-data:
    driver: local
    driver_opts:
      # ホストマシンの特定のファイルやディレクトリをコンテナの特定の場所にマウント
      # type: none o: bindでもupはできるが、怪しい
      type: none
      device: ${VOLUME_PATH}wordpress
      # device: /home/hyunosuk/data/mysql
      # o: bindをつけないとエラーが出てしまう
      # 冗長じゃないのかな？
      o: bind

networks:
  inception_network: