version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: container_nginx
    networks:
      - inception_network
    ports:
      - "443:443"

  wordpress:
    build: ./requirements/wordpress
    container_name: container_wordpress
    networks:
      - inception_network
    env_file:
      - .env


# volumesはコンテナ間でデータを共有したり、データを永続的に残せる
# networksはコンテナ間の通信を可能にする
# buildはディレクトリを指定すれば、そのディレクトリにあるDockerfileを使ってイメージを作成する

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      # ホストマシンの特定のファイルやディレクトリをコンテナの特定の場所にマウント
      # type: none o: bindでもupはできるが、怪しい
      type: bind
      device: /Users/hommayunosuke/Documents/ft.dir/Rank05/Inception/data/mysql
#      device: /home/hyunosuk/data/mysql
      # o: bindをつけないとエラーが出てしまう
      # 冗長じゃないのかな？
      o: bind

networks:
  inception_network: